[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[global]
showWarningOnDirectExecution = false

[server]
runOnSave = true
# fileWatcherType = "none"

[runner]
fastReruns = true

[browser]
gatherUsageStats = false
